# Generated by Django 3.1.6 on 2024-03-09 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Article'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Catégorie'},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
    ]
